version: '3'

services:
  bot:
    build: .
    container_name: poe-telegram-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POE_API_KEY=${POE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ADMIN_USERS=${ADMIN_USERS}
      - ALLOWED_USERS=${ALLOWED_USERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data  # 数据目录挂载，用于存储统计数据 